[package]
name = "xcfg-derive"
version = "0.1.0"
edition = "2021"
description = "A simple configuration file parser for Rust"
license = "MIT"
repository = "https://github.com/kumudiaorong/xcfg-rs.git"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.46"
