[package]
name = "xcfg-derive"
version = "0.1.0"
edition = "2024"
description = "A simple configuration file parser for Rust"
license = "MIT"
repository = "https://github.com/km0e/xcfg-rs.git"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
